feat: 관리자용 게시글, 퀴즈, 신고, 사용자 Swagger 작성 및 삭제 예외처리 변경
YU-Quiz/was pull request #16
Opened 2024-08-11 16:32 UTC by gardenzeeero

## 개요
관리자용 게시글, 퀴즈, 신고, 사용자 관련 Swagger 작성

게시글과 퀴즈를 삭제하는 서비스에서 예외처리를 변경

## 구현 사항
관리자용 게시글, 퀴즈, 신고, 사용자 관련 Swagger를 작성했습니다.

기존에는 게시글이나 퀴즈를 delete할 때 없는 엔티티인 경우, 404 상태코드와 함께 없는 엔티티라는 메세지를 보내도록 설계되어 있었습니다.   
EmptyResultDataAccessException이 터지면 404를 보내주던 방식이었습니다.

하지만 Spring Data Jpa를 확인한 결과, 삭제 쿼리의 경우 없는 엔티티더라도 삭제성공으로 처리하는 것을 알게 되었습니다.
즉, EmptyResultDataAccessException는 터지지 않고 204(No Content)만을 반환하게 됩니다.

따라서, 예외를 처리해주는 로직을 없애고 단순히 delete문으로 대체하였습니다.

2024-08-11 16:49 UTC, DaeYoung0726 requested changes
고생하셨습니다!
찾아낸 오류 코드 참고해서 수정하도록 하겠습니다!

2024-08-11 16:49 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/post/service/AdminPostService.java
> -        }
테스트해서 못찾은 부분을 찾아주셨네요! 참고해서 제 코드에서도 고치도록 하겠습니다👍👍

2024-08-11 16:50 UTC, DaeYoung0726 approved these changes

2024-08-11 16:50 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/post/service/AdminPostService.java
> -        }
어이고.. 거절은 실수

2024-08-12 03:04 UTC, Uralauah reviewed
고생하셨습니다~

2024-08-12 03:04 UTC, Uralauah commented on src/main/java/yuquiz/domain/post/service/AdminPostService.java
> -        }
그런 오류가 생기는 줄은 몰랐네요..
그럼 만약 사용자가 존재하지 않는 postId를 삭제하려고 하면 어떻게 되나요?
저는 그 경우를 피하고자 `EmptyResultDataAccessException` 처리를 한거였는데
저 부분이 없어도 자동으로 처리가 되는걸까요?

2024-08-12 03:37 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/post/service/AdminPostService.java
> -        }
디비에는 그대로 전달이 되고, 삭제되는 것이 없더라도 디비는 그에 맞는 값을 삭제하려고 시도합니다.
이러한 시도를 하기때문에 빈 값이 있더라도 예외처리를 안하고 정상적으로 작동이 되었다는 문구가 뜨게 됩니다!

2024-08-12 08:34 UTC, merged