refact: FullTextIndex를 활용한 검색 구현
YU-Quiz/was pull request #64
Opened 2024-10-05 10:29 UTC by Uralauah

## 개요
기존에 Like를 활용하여 비효율적으로 검색하던 로직을 Full-Text Index를 활용하여 더욱 효율적으로 동작하도록 하였습니다.
현재는 퀴즈 검색 기능만 구현했습니다.
추후 게시글에도 적용하도록 하겠습니다.

## 구현사항
* Full-Text Index를 도입하여 검색 성능 향상
* 기존과 동일한 역할을 하도록 구현함

## 기타
1. 기존에 정렬 방식을 선택하기 위해 사용했던 `QuizSortType`을 그대로 사용하고 싶었으나, 현재 코드에서는 Sort 로 정렬하는 것이 아닌 `OrderSpecifier`를 이용하기 때문에 String으로 sort를 입력받도록 수정함.
2. QueryDSL을 사용하지 않고 Query문을 작성하여 구현하려고 하였으나 QueryDSL을 활용하는 것이 더 효율적이라는 생각에 QueryDSL 을 사용하여 구현함.
3. 현재 방법으로 검색 기능을 구현했을 때, `CustomQuizRepository` 의 getQuizzes로 퀴즈를 불러오고 바로 반환하려고 하면 오류가 생김. 따라서 `QuizListRes`라는 새로운 DTO를 이용하여 Page와 비슷한 형식으로 반환하도록 구현함.
4. 해당 Full-Text Index는 N-Gram으로 구현됨(검색어가 완전히 똑같지 않더라도 유사하면 검색됨) 아직 YU-Quiz 데이터베이스에는 적용되지 않음.
5. 검색에는 자연어 검색이 사용됨(키워드를 '단어1 단어2'와같이 띄어쓰기로 제공하면 단어1 또는 단어2가 포함된 퀴즈를 모두 찾아냄)
6. 컨트롤러에서 매개변수로 page를 받는게 아니라 Pageable을 직접 받아줄 수 있길래 한번 적용해보았습니다. 기존 방식과 해당 방식 중 어떤 것이 나을까요?

## 성능 비교 (데이터양 : 38,105)
기존의 LIKE를 활용한 검색 
<img width="677" alt="Pasted Graphic 3" src="https://github.com/user-attachments/assets/a783e939-e9cc-4a74-9d20-85822f25786f">

Full-Text Index를 활용한 검색
![image](https://github.com/user-attachments/assets/b76a57de-7d5c-458e-a848-cf995d3a7a2b)

## 수정사항
퀴즈 목록 조회 시 퀴즈 시도 여부를 가져오기 위해 해당 페이지의 데이터 개수만큼 triedQuizRepository에 접근하여 총 20번의 쿼리가 더 나가는 것을 발견하고 최소한의 쿼리문을 날리기 위해 해당 부분을 수정하였습니다.

성능 또한 어느정도 개선이 되었습니다.
<img width="680" alt="image" src="https://github.com/user-attachments/assets/27aff8fc-cf7f-4a99-87bc-f4f8f6cb31ec">

2024-10-06 09:07 UTC, daeyoung0726 reviewed
고생하셨습니다!
`CustomQuizRepositoryImpl`에서
`import static yuquiz.domain.quiz.entity.QQuiz.quiz;` 해당 클래스 위치를 찾는데 애 좀 먹었네요 (원영님도 저와 같은 경우라면, buildjar 하시면 `/build/generated/sources/annotationProcessor/~~~`에 있습니다!)

그 외에, 다른 의견 남겨놓겠습니다.

2024-10-07 07:33 UTC, daeyoung0726 approved these changes
고생하셨습니다!

2024-10-08 11:00 UTC, gardenzeeero requested changes
수고하셨습니다. QueryDSL을 안써봐서 그거에 대해 찾아본다고 시간이 좀 걸렸습니다.

제가 보기에는 Page 뿐만 아니라 설계상 문제가 되는 부분이 보여 말씀드립니당~

2024-10-10 10:58 UTC, daeyoung0726 approved these changes

2024-10-12 06:04 UTC, gardenzeeero approved these changes

2024-10-12 09:26 UTC, merged