feat: 퀴즈 생성, 수정, 삭제 구현
YU-Quiz/was pull request #8
Opened 2024-08-09 12:15 UTC by Uralauah

## 개요
퀴즈 생성, 수정, 삭제 구현

## 구현사항
* 퀴즈 생성 기능 
  * 퀴즈 생성 시 입력 검증
* 퀴즈 수정 기능
  * 퀴즈 수정 시 사용자 확인 후 작성자만 수정 가능
  * 입력 검증
* 퀴즈 삭제 기능
  * 퀴즈 삭제 시 사용자 확인 후 작성자만 삭제 가능

## 테스트
1. 퀴즈 생성 성공.
<img width="678" alt="image" src="https://github.com/user-attachments/assets/32d85b91-1599-43ab-a26d-c3e1ea0fe7cb">

2. 퀴즈 생성 실패 (입력 데이터 누락)
![image](https://github.com/user-attachments/assets/150111c6-8e5f-4db1-83e7-e17dc3551577)

3. 퀴즈 수정 성공
![image](https://github.com/user-attachments/assets/93782901-3419-42be-9bb4-63886ffdb5aa)

4. 퀴즈 수정 실패 (작성자 아님) 
![image](https://github.com/user-attachments/assets/d6690d8f-a026-49c0-8e1f-5fba63c361bb)

5. 퀴즈 수정 실패 (입력 데이터 누락)
<img width="672" alt="image" src="https://github.com/user-attachments/assets/9b8e002d-6899-4174-9f75-b9108f36f0dc">

6. 퀴즈 삭제 성공
보통 삭제할 때에는 삭제에 성공해서 해당 데이터가 이제 존재하지 않는다는 의미에서
HttpStatus를 204(No Content)를 많이 한다고 합니다.
저도 이번에 안 사실이라 혹시 아니라면 알려주시길 바랍니다.
![image](https://github.com/user-attachments/assets/f3684d70-a7ef-4a6b-88aa-b22e68725616)

7. 퀴즈 삭제 실패 (작성자 아님)
![image](https://github.com/user-attachments/assets/ac5d9210-d05e-4305-8a26-b0411f516f46)

2024-08-09 14:25 UTC, DaeYoung0726 requested changes
고생하셨습니다!
몇 가지 저의 의견이 있어 코멘트 달아놓겠습니다!

2024-08-09 14:25 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/quiz/controller/QuizController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(SuccessRes.from("퀴즈 생성 성공."));
Principal principal을 통해서 사용자의 username을 불러오는 것 같습니다!
Principal을 사용하면 단순히 사용자의 username을 불러오는걸로 알고 있는데,
사용자의 id(pk값)을 불러오는 것은 어떻게 생각하시나요?

왜냐하면 id는 변경되지 않은 불변의 값이기 때문에 id를 통해 불러오는건 어떨까 라는 의견입니다!

Principal principal 대신에 아래와 같은 코드를 사용할 수 있습니다!
`@AuthenticationPrincipal SecurityUserDetails userDetails` 이러한 코드를 사용하면, 인증된 사용자의 정보에서 SecurityUserDetails에 등록된 정보를 모두 불러올 수 있습니다.

만약 위 코드를 사용한다면,  `quizService.quizCreate(quizCreateReq, userDetails.getId());` 를 사용하여 서비스 로직에서 findById를 사용하면 되지만, 제가 까먹고 SecurityUserDetails 에서 getId() 메서드 설정을 안했어요....
 이 메서드에 대해서는 develop브렌치에 추가해놓도록 하겠습니다!

2024-08-09 14:25 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/quiz/controller/QuizController.java
> +    @PostMapping
이건 개인적인 의견이긴 한데, 저는 새로운 내용을 적게되면 개행을 해서 구분을 시켜 가독성을 높이려고 하거든요!
저는 개인적으로 봤을때 붙어있으면 코드가 복잡해보이는 느낌이 들어서요
이 부분에 대해서 어떻게 생각하시나요?

2024-08-09 14:25 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/subject/exception/SubjectExceptionCode.java
> +        return null;
이부분에서 반환이 제대로 설정되어 있지 않습니다!
getStauts()에서는 status, getMessage()에서는 message를 반환해야 해요!

2024-08-09 14:25 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/quiz/dto/QuizCreateReq.java
> +public class QuizCreateReq {
저희 dto같은 경우에 카톡방에서 말했을 때 record를 사용하기로 했어요!
record로 변경해줄 수 있나요??

패키지 domain.user.dto에 보면 SignUpReq 와 유사한데, 그것과 비교하며 작성하면 될 것 같아요!

2024-08-09 14:26 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/quiz/dto/QuizReq.java
> +    List<String> choices;
이부분은 나중에 프론트와 의견을 나누고 길이 제한을 넣는게 좋을 것 같습니다!

2024-08-09 14:32 UTC, Uralauah commented on src/main/java/yuquiz/domain/subject/exception/SubjectExceptionCode.java
> +        return null;
맞네요..
ide에서 자동으로 해주는 override만 하고 반환을 수정해주지 않았네요

2024-08-09 14:32 UTC, Uralauah commented on src/main/java/yuquiz/domain/quiz/dto/QuizCreateReq.java
> +public class QuizCreateReq {
앗...
습관적으로 class로 만들어버렸네요
좋은 지적입니다

2024-08-09 14:41 UTC, Uralauah commented on src/main/java/yuquiz/domain/quiz/dto/QuizCreateReq.java
> +public class QuizCreateReq {
근데 문제가 있습니다.
지금 퀴즈를 생성할 때, 아래의 코드와 같이 해당 dto를 전달받아서 작성자와 과목을 dto에 설정하고 
해당 dto를 엔티티로 변환해주는 과정으로 코드를 작성했는데
```java
public void createQuiz(QuizReq quizReq, Principal principal) {
        User user = findUserByPrincipal(principal);

        Subject subject = subjectRepository.findById(quizReq.getSubjectId())
                .orElseThrow(() -> new CustomException(SubjectExceptionCode.INVALID_ID));

        quizReq.setWriter(user);
        quizReq.setSubject(subject);

        Quiz quiz = quizReq.toEntity();
        quizRepository.save(quiz);
    }
``` 
record를 사용하면 불변성이 있어 작성자와 과목을 집어넣을 수가 없는데
이렇게되면 아래와 비슷하게 새로운 인스턴스를 생성해서 그걸 엔티티로 변환해주는 방식으로 진행하는게 맞을까요?
```java
QuizReq saveQuizReq = new QuizReq(
        quizReq.title(),
        quizReq.question(),
        quizReq.quizImg(),
        quizReq.answer(),
        quizReq.quizType(),
        quizReq.choices(),
        subject,            
        user                
);
```

2024-08-09 14:48 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/quiz/dto/QuizCreateReq.java
> +public class QuizCreateReq {
SignUpReq에서 작성한 dto를 가져와 빌려 쓰자면
``` java
public User toEntity(String encodePassword) {
        return User.builder()
                .username(username)
                .password(encodePassword)
                .nickname(nickname)
                .email(email)
                .majorName(majorName)
                .agreeEmail(agreeEmail)
                .build();
    }
```

이렇게 쓰인걸 볼 수 있습니다!

그래서
``` java
public record QuizCreateReq(
  @NotBlank(message = "제목은 필수 입력입니다.")
    String title,

    @NotBlank(message = "질문은 필수 입력입니다.")
    String question,

    List<String> quizImg,

    @NotBlank(message = "정답은 필수 입력입니다.")
    String answer,

    @NotBlank(message = "퀴즈 유형은 필수 입력입니다.")
    QuizType quizType,

    List<String> choices,

    @NotBlank(message = "과목은 필수 입력입니다.")
    Long subjectId
) {

    public Quiz toEntity(User writer, Subject subject) {
        return Quiz.builder()
                .title(this.title)
                .question(this.question)
                .quizImgs(this.quizImg)
                .answer(this.answer)
                .quizType(this.quizType)
                .choices(this.choices)
                .writer(writer)
                .subject(subject)
                .build();
    }
}
```

이런형식으로 쓴다면 해결될 것 같습니다!
코드에 작성안해보고 여기서 바로 작성한거라 오류가 있을 수 있지만 위와 같은 방식으로 쓰면 record를 쓰더라도 승현님이 사용하신 방법을 사용할 수 있을 것 같습니다

그러면 service에서 `Quiz quiz = quizReq.toEntity(user, subject);`  같은 코드로 바뀌게 되겠죠?

2024-08-09 14:53 UTC, DaeYoung0726 reviewed
추가적인 코멘트 보다가 생각나서 하나만 더 남겨놓을게요!

2024-08-09 14:53 UTC, DaeYoung0726 commented on src/main/java/yuquiz/domain/quiz/controller/QuizController.java
> +    public ResponseEntity<?> updateQuiz(
delete와 put할때 api명세서 보면 :quizId있어서 이것이 requestParam으로 오해하신 것 같습니다!
이것은 PathVariable이고  restful하게 작성하려면 PathVariable사용 방식이 옳다고 느껴집니다!

2024-08-09 15:14 UTC, DaeYoung0726 approved these changes

2024-08-10 05:44 UTC, gardenzeeero approved these changes
지적사항 외에는 모두 깔끔하네요 좋습니다.

2024-08-10 05:46 UTC, merged